### PR TITLE
Refactored to Support Livewire v3

### PR DESCRIPTION
**Pull request by coolsam726**
Livewire v3 is a ground-up rewrite of Livewire, with a few breaking changes.

The following are some of the changes that affect this package:
- `Livewire\\Commands` namespace has moved to `\Livewire\Features\SupportConsoleCommands\Commands`
- The default path for livewire components has moved from `Http\\Livewire` to `Livewire`

This PR is intended for the next major release of the package since it doesn't have backward compatibility with Livewire 2.

### CODE REVIEW

**Comment by mhmiton** [comment]
@coolsam726 Thanks for this PR. I will merge this soon.

**Comment by tomgrv** [comment]
> This PR is intended for the next major release of the package since it doesn't have backward compatibility with Livewire 2.

It Should be a v2.0.0 then ?

**Comment by mhmiton** [comment]
@tomgrv Sorry, I did not understand properly. Do you mean that, the latest release version should be v2.0.0 instead of v1.7.0 for this package?

**Comment by tomgrv** [comment]
> @tomgrv Sorry, I did not understand properly. Do you mean that, the latest release version should be v2.0.0 instead of v1.7.0 for this package?

Sorry for the lack of clarity.

Yes, since you introduce a breaking change, version should be 2.0.0 to reflect it (as per semver guidelines) it and prevent automatic updates.

**Comment by mhmiton** [comment]
@tomgrv Oh, ok. Thanks for your suggestions. I will change it.

**Pull request merged**
